site_name: storio-della-musica-pop-I

site_author: Raffaella Migliaccio

copyright: "&copy; Raffaella Migliaccio, 2020"


docs_dir: src

#theme:
#  name: material
#  icon:
#    logo: material/circle-multiple
#  palette:
#    primary: 'blue grey'
#  font:
#    text: 'Ubuntu'
#    code: 'Ubuntu mono'
#  language: 'en'
#  use_directory_urls: true

#repo_name: 'scythe-suite/danake'
#repo_url: 'https://github.com/scythe-suite/danake'
#edit_uri: ''
#
#extra:
#  search:
#    lang:
#      - 'en'
#  social:
#  - icon: 'fontawesome/brands/github-alt'
#    link: 'https://github.com/mapio'
#  - icon: 'fontawesome/brands/twitter'
#    link: 'https://twitter.com/mapio'
#  - icon: 'fontawesome/brands/linkedin'
#    link: 'https://www.linkedin.com/in/massimosantini/'
#
#markdown_extensions: #  https://python-markdown.github.io/extensions/
#  - toc:
#        permalink: "#"
#        toc_depth: 2-6
#  - admonition
#  - pymdownx.details
#  - pymdownx.extra
#  - pymdownx.inlinehilite
#  - pymdownx.superfences
#
#extra_css:
#  - css/extra.css
#
#extra_javascript:
#  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js
#
nav:
  - index.md
  - 2.md
  - 3.md
  - 4.md
  - 5.md